language: python
python:
    - "3.4"
before_install:
   #Uses miniconda installation of scientific python packages instead of building from source
   #or using old versions supplied by apt-get. Source: https://gist.github.com/dan-blanchard/7045057
   - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then 
        wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh; 
    else 
        wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi
   - chmod +x miniconda.sh
   - ./miniconda.sh -b -p $HOME/miniconda
   - export PATH=/home/travis/miniconda/bin:$PATH
   - hash -r
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - sudo apt-get update -qq
install:
   - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
   - source activate test-environment
   - sudo apt-get install -qq build-essential libgsl0-dev samtools bowtie2 
   - conda install snakemake
script: nosetests
